# Generated by Django 5.2.9 on 2025-12-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_8a7c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_f77590_idx',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='email_bookings',
            new_name='email_notifications',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='email_messages',
            new_name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='digest_frequency',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_payments',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_promotional',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_reviews',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_system',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='in_app_bookings',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='in_app_messages',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='in_app_payments',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='in_app_reviews',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='in_app_system',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_bookings',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_messages',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_payments',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_reviews',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_end',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_start',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('booking', 'Booking Update'), ('review', 'New Review'), ('system', 'System Notification')], max_length=20),
        ),
    ]
