# Generated by Django 5.2.9 on 2026-01-01 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
