# Generated by Django 5.2.9 on 2026-01-01 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Unique email address used for login.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=False, verbose_name='marketing opt-in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='privacy policy accepted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Indicates if the user has filled out their specialized profile (Caregiver/Client).', verbose_name='profile completed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='terms accepted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('caregiver', 'Caregiver'), ('admin', 'Administrator')], default='client', max_length=20, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional dummy field for legacy compatibility. Not used for login.', max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified Professional'), ('rejected', 'Documentation Rejected')], default='pending', max_length=20, verbose_name='verification status'),
        ),
    ]
